/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f9f9fb',
        'surface-dim': '#d9dadc',
        'surface-bright': '#f9f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f3f3f5',
        'surface-container': '#eeeef0',
        'surface-container-high': '#e8e8ea',
        'surface-container-highest': '#e2e2e4',
        'on-surface': '#1a1c1d',
        'on-surface-variant': '#4c4546',
        'inverse-surface': '#2f3132',
        'inverse-on-surface': '#f0f0f2',
        outline: '#7e7576',
        'outline-variant': '#cfc4c5',
        'surface-tint': '#5e5e5e',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#1b1b1b',
        'on-primary-container': '#848484',
        'inverse-primary': '#c6c6c6',
        secondary: '#5e5e5e',
        'on-secondary': '#ffffff',
        'secondary-container': '#e1dfdf',
        'on-secondary-container': '#626262',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#1a1c1c',
        'on-tertiary-container': '#838484',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#f9f9fb',
        'on-background': '#1a1c1d',
        'surface-variant': '#e2e2e4',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'h1': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'h2': ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '500' }],
        'button': ['14px', { lineHeight: '1', letterSpacing: '0.01em', fontWeight: '500' }],
      },
      borderRadius: {
        'sm': '0.25rem',
        DEFAULT: '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'unit': '4px',
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
        'gutter': '20px',
        'margin-page': '32px',
      },
    },
  },
  plugins: [],
}
